package com.mohammedmustafa.smartcompany;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.graphics.Color;import android.print.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 DB db; LinearLayout content; final int green=Color.rgb(11,93,59);
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this); if(!trial()){lock("انتهت التجربة المجانية. الرجاء التواصل مع الدعم.");}else login();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(18,14,18,14);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setPadding(18,8,18,8);return x;}
 void page(String h){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.rgb(248,249,250));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(green);TextView q=t(h,20);q.setTextColor(Color.WHITE);bar.addView(q,new LinearLayout.LayoutParams(0,-2,1));Button home=b("الرئيسية");home.setTextColor(Color.WHITE);home.setOnClickListener(v->dashboard());bar.addView(home);r.addView(bar);ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);s.addView(content);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);}
 boolean trial(){android.content.SharedPreferences p=getSharedPreferences("trial",0);long f=p.getLong("first",0);if(f==0){f=System.currentTimeMillis();p.edit().putLong("first",f).apply();}return System.currentTimeMillis()-f<7L*86400000L;}
 void lock(String msg){page("الاشتراك");content.addView(t(msg,20));Button w=b("التواصل مع الدعم");content.addView(w);w.setOnClickListener(v->open("https://wa.me/249121851285"));content.addView(t("ملاحظة: لا يوجد كود تفعيل ثابت داخل الإصدار 2.0. نظام الترخيص النهائي سيستخدم ترخيصًا موقّعًا من الخادم.",14));}
 void login(){page("شركة محمد مصطفي الذكية");content.addView(t("المحاسبة والمخزون — الإصدار 2.0",24));android.content.SharedPreferences p=getSharedPreferences("security",0);if(!p.contains("pin")){content.addView(t("أنشئ رمز دخول خاصًا بك (4 أرقام على الأقل).",16));EditText x=e("رمز الدخول");x.setInputType(2|0x10);content.addView(x);Button s=b("حفظ الرمز والدخول");content.addView(s);s.setOnClickListener(v->{String z=x.getText().toString();if(z.length()<4){toast("الرمز قصير");return;}p.edit().putString("pin",z).apply();dashboard();});}else{EditText x=e("رمز الدخول");x.setInputType(2|0x10);content.addView(x);Button s=b("دخول");content.addView(s);s.setOnClickListener(v->{if(x.getText().toString().equals(p.getString("pin","")))dashboard();else toast("رمز الدخول غير صحيح");});}}
 void dashboard(){page("لوحة التحكم");content.addView(t("مركز إدارة النشاط",24));content.addView(t(summary(),16));String[] a={"الفواتير والمبيعات","المشتريات","الأصناف والمخزون","العملاء","الموردون","الصندوق والمصروفات","الموظفون","التقارير والتحليل","النسخ الاحتياطي","الدعم"};for(String n:a){Button x=b(n);content.addView(x);x.setOnClickListener(v->{switch(n){case"الفواتير والمبيعات":invoice(false);break;case"المشتريات":invoice(true);break;case"الأصناف والمخزون":products();break;case"العملاء":party("customers","العملاء");break;case"الموردون":party("suppliers","الموردون");break;case"الصندوق والمصروفات":cash();break;case"الموظفون":party("employees","الموظفون");break;case"التقارير والتحليل":reports();break;case"النسخ الاحتياطي":backup();break;default:open("https://wa.me/249121851285");}});}}
 String summary(){Cursor c=db.q("SELECT COALESCE(SUM(CASE WHEN type='SALE' THEN total ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='PURCHASE' THEN total ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='EXPENSE' THEN total ELSE 0 END),0) FROM transactions");double s=0,p=0,x=0;if(c.moveToFirst()){s=c.getDouble(0);p=c.getDouble(1);x=c.getDouble(2);}c.close();return"المبيعات: "+fmt(s)+" | المشتريات: "+fmt(p)+" | المصروفات: "+fmt(x);}
 void products(){page("الأصناف والمخزون");EditText n=e("اسم الصنف"),q=e("الرصيد الافتتاحي"),p=e("سعر البيع"),c=e("تكلفة الوحدة"),r=e("حد إعادة الطلب");for(EditText x:new EditText[]{n,q,p,c,r}){x.setInputType(2);if(x==n)x.setInputType(1);content.addView(x);}Button add=b("إضافة الصنف");content.addView(add);add.setOnClickListener(v->{if(n.getText().toString().trim().isEmpty())return;db.exec("INSERT INTO products(name,qty,sale_price,cost,reorder) VALUES(?,?,?,?,?)",n.getText().toString(),num(q),num(p),num(c),num(r));n.setText("");q.setText("");p.setText("");c.setText("");r.setText("");products();});Cursor z=db.q("SELECT name,qty,sale_price,cost,reorder FROM products ORDER BY id DESC");while(z.moveToNext())content.addView(t(z.getString(0)+" | رصيد "+z.getDouble(1)+" | بيع "+fmt(z.getDouble(2))+" | تكلفة "+fmt(z.getDouble(3))+(z.getDouble(1)<=z.getDouble(4)?" | ⚠ إعادة طلب":""),15));z.close();}
 void invoice(boolean purchase){page(purchase?"فاتورة شراء":"فاتورة بيع");EditText customer=e(purchase?"المورد":"العميل"),item=e("اسم الصنف"),qty=e("الكمية"),price=e("السعر"),paid=e("المدفوع");for(EditText x:new EditText[]{customer,item,qty,price,paid})content.addView(x);Button save=b("حفظ الفاتورة");content.addView(save);save.setOnClickListener(v->{Cursor c=db.q("SELECT id,qty,cost,sale_price FROM products WHERE name=?",item.getText().toString());if(!c.moveToFirst()){c.close();toast("الصنف غير موجود");return;}double q=num(qty),pr=num(price),old=c.getDouble(1);if(q<=0){c.close();return;}double next=purchase?old+q:old-q;if(next<0){c.close();toast("الرصيد غير كافٍ");return;}long pid=c.getLong(0);c.close();db.tx("UPDATE products SET qty=? WHERE id=?",next,pid);String type=purchase?"PURCHASE":"SALE";double total=q*pr, pay=num(paid);db.tx("INSERT INTO transactions(type,party,total,paid,remaining,created_at) VALUES(?,?,?,?,?,?)",type,customer.getText().toString(),total,pay,Math.max(0,total-pay),System.currentTimeMillis());db.tx("INSERT INTO invoice_items(transaction_id,product_id,qty,price,cost) VALUES((SELECT max(id) FROM transactions),?,?,?,?)",pid,q,pr,0);toast("تم حفظ الفاتورة وتحديث المخزون");dashboard();});}
 void party(String table,String title){page(title);EditText n=e("الاسم");content.addView(n);Button add=b("إضافة");content.addView(add);add.setOnClickListener(v->{if(!n.getText().toString().trim().isEmpty())db.exec("INSERT INTO "+table+"(name) VALUES(?)",n.getText().toString());n.setText("");party(table,title);});Cursor c=db.q("SELECT name FROM "+table+" ORDER BY id DESC");while(c.moveToNext())content.addView(t("• "+c.getString(0),16));c.close();}
 void cash(){page("الصندوق والمصروفات");EditText desc=e("البيان"),amt=e("المبلغ");amt.setInputType(2);content.addView(desc);content.addView(amt);Button add=b("تسجيل مصروف");content.addView(add);add.setOnClickListener(v->{double x=num(amt);if(x<=0)return;db.exec("INSERT INTO transactions(type,party,total,paid,remaining,created_at) VALUES('EXPENSE',?,?,?,?,?)",desc.getText().toString(),x,x,0,System.currentTimeMillis());toast("تم تسجيل المصروف");dashboard();});}
 void reports(){page("التقارير والتحليل");Cursor c=db.q("SELECT type,COALESCE(SUM(total),0) FROM transactions GROUP BY type");while(c.moveToNext())content.addView(t(c.getString(0)+" : "+fmt(c.getDouble(1)),19));c.close();Cursor p=db.q("SELECT COALESCE(SUM((i.price-i.cost)*i.qty),0) FROM invoice_items i JOIN transactions t ON t.id=i.transaction_id WHERE t.type='SALE'");double gp=p.moveToFirst()?p.getDouble(0):0;p.close();content.addView(t("مجمل الربح المحسوب من البنود: "+fmt(gp),21));content.addView(t("تنبيه: هذا تقرير تشغيلي أولي؛ القوائم المالية الكاملة ودفتر الأستاذ ستدخل في المرحلة المحاسبية التالية بعد اختبار القيود.",14));}
 void backup(){page("النسخ الاحتياطي");Button x=b("تصدير نسخة قاعدة البيانات");content.addView(x);x.setOnClickListener(v->{toast("النسخة المحلية محفوظة داخل بيانات التطبيق. تصدير ملف خارجي آمن سيضاف مع مركز النسخ الاحتياطي 2.1.");});content.addView(t("لا نعتبر النسخ الاحتياطي التجاري مكتملًا حتى يتم اختبار الاستعادة فعليًا.",15));}
 double num(EditText x){try{return Double.parseDouble(x.getText().toString());}catch(Exception z){return 0;}}String fmt(double x){return String.format(Locale.US,"%,.2f",x);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(u)));}catch(Exception z){}}
 public void onBackPressed(){dashboard();}
 static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"smartcompany2.db",null,2);}public void onCreate(SQLiteDatabase d){schema(d);}public void onUpgrade(SQLiteDatabase d,int o,int n){schema(d);}void schema(SQLiteDatabase d){d.execSQL("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,qty REAL NOT NULL DEFAULT 0,sale_price REAL NOT NULL DEFAULT 0,cost REAL NOT NULL DEFAULT 0,reorder REAL NOT NULL DEFAULT 0)");d.execSQL("CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,party TEXT,total REAL NOT NULL,paid REAL NOT NULL DEFAULT 0,remaining REAL NOT NULL DEFAULT 0,created_at INTEGER)");d.execSQL("CREATE TABLE IF NOT EXISTS invoice_items(id INTEGER PRIMARY KEY AUTOINCREMENT,transaction_id INTEGER,product_id INTEGER,qty REAL,price REAL,cost REAL)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_invoice_items_tx ON invoice_items(transaction_id)");}void exec(String s,Object...a){tx(s,a);}void tx(String s,Object...a){SQLiteDatabase d=getWritableDatabase();SQLiteStatement q=d.compileStatement(s);for(int i=0;i<a.length;i++){Object v=a[i];if(v instanceof Number)q.bindDouble(i+1,((Number)v).doubleValue());else q.bindString(i+1,String.valueOf(v));}q.execute();}Cursor q(String s,String...a){return getReadableDatabase().rawQuery(s,a);}}
}
