package com.mohammedmustafa.smartcompany;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.graphics.Color;import android.print.*;import android.view.*;import android.widget.*;import java.util.*;import java.io.*;

public class MainActivity extends Activity{
 DB db; LinearLayout content; final int green=Color.rgb(11,93,59);
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this); if(!trial()){lock("انتهت التجربة المجانية. الرجاء التواصل مع الدعم.");}else login();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(18,14,18,14);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setPadding(18,8,18,8);return x;}
 void page(String h){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.rgb(248,249,250));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(green);TextView q=t(h,20);q.setTextColor(Color.WHITE);bar.addView(q,new LinearLayout.LayoutParams(0,-2,1));Button home=b("الرئيسية");home.setTextColor(Color.WHITE);home.setOnClickListener(v->dashboard());bar.addView(home);r.addView(bar);ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);s.addView(content);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);}
 boolean trial(){android.content.SharedPreferences p=getSharedPreferences("trial",0);long f=p.getLong("first",0);if(f==0){f=System.currentTimeMillis();p.edit().putLong("first",f).apply();}return System.currentTimeMillis()-f<7L*86400000L;}
 void lock(String msg){page("الاشتراك");content.addView(t(msg,20));Button w=b("التواصل مع الدعم");content.addView(w);w.setOnClickListener(v->open("https://wa.me/249121851285"));content.addView(t("ملاحظة: لا يوجد كود تفعيل ثابت داخل الإصدار 2.0. نظام الترخيص النهائي سيستخدم ترخيصًا موقّعًا من الخادم.",14));}
 void login(){page("شركة محمد مصطفي الذكية");content.addView(t("المحاسبة والمخزون — الإصدار 2.0",24));android.content.SharedPreferences p=getSharedPreferences("security",0);if(!p.contains("pin")){content.addView(t("أنشئ رمز دخول خاصًا بك (4 أرقام على الأقل).",16));EditText x=e("رمز الدخول");x.setInputType(2|0x10);content.addView(x);Button s=b("حفظ الرمز والدخول");content.addView(s);s.setOnClickListener(v->{String z=x.getText().toString();if(z.length()<4){toast("الرمز قصير");return;}p.edit().putString("pin",z).apply();dashboard();});}else{EditText x=e("رمز الدخول");x.setInputType(2|0x10);content.addView(x);Button s=b("دخول");content.addView(s);s.setOnClickListener(v->{if(x.getText().toString().equals(p.getString("pin","")))dashboard();else toast("رمز الدخول غير صحيح");});}}
 void dashboard(){page("لوحة التحكم");content.addView(t("مركز إدارة النشاط",24));content.addView(t(summary(),16));String[] a={"الفواتير والمبيعات","المشتريات","الأصناف والمخزون","العملاء","الموردون","الصندوق والمصروفات","الموظفون","التقارير والتحليل","النسخ الاحتياطي","الدعم"};for(String n:a){Button x=b(n);content.addView(x);x.setOnClickListener(v->{switch(n){case"الفواتير والمبيعات":invoice(false);break;case"المشتريات":invoice(true);break;case"الأصناف والمخزون":products();break;case"العملاء":party("customers","العملاء");break;case"الموردون":party("suppliers","الموردون");break;case"الصندوق والمصروفات":cash();break;case"الموظفون":party("employees","الموظفون");break;case"التقارير والتحليل":reports();break;case"النسخ الاحتياطي":backup();break;default:open("https://wa.me/249121851285");}});}}
 String summary(){Cursor c=db.q("SELECT COALESCE(SUM(CASE WHEN type='SALE' THEN total ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='PURCHASE' THEN total ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='EXPENSE' THEN total ELSE 0 END),0) FROM transactions");double s=0,p=0,x=0;if(c.moveToFirst()){s=c.getDouble(0);p=c.getDouble(1);x=c.getDouble(2);}c.close();return"المبيعات: "+fmt(s)+" | المشتريات: "+fmt(p)+" | المصروفات: "+fmt(x);}
 void products(){page("الأصناف والمخزون");EditText n=e("اسم الصنف"),q=e("الرصيد الافتتاحي"),p=e("سعر البيع"),c=e("تكلفة الوحدة"),r=e("حد إعادة الطلب");for(EditText x:new EditText[]{n,q,p,c,r}){x.setInputType(2);if(x==n)x.setInputType(1);content.addView(x);}Button add=b("إضافة الصنف");content.addView(add);add.setOnClickListener(v->{if(n.getText().toString().trim().isEmpty())return;db.exec("INSERT INTO products(name,qty,sale_price,cost,reorder) VALUES(?,?,?,?,?)",n.getText().toString(),num(q),num(p),num(c),num(r));n.setText("");q.setText("");p.setText("");c.setText("");r.setText("");products();});Cursor z=db.q("SELECT name,qty,sale_price,cost,reorder FROM products ORDER BY id DESC");while(z.moveToNext())content.addView(t(z.getString(0)+" | رصيد "+z.getDouble(1)+" | بيع "+fmt(z.getDouble(2))+" | تكلفة "+fmt(z.getDouble(3))+(z.getDouble(1)<=z.getDouble(4)?" | ⚠ إعادة طلب":""),15));z.close();}
 void invoice(boolean purchase){page(purchase?"فاتورة شراء":"فاتورة بيع");EditText customer=e(purchase?"المورد":"العميل"),item=e("اسم الصنف"),qty=e("الكمية"),price=e("السعر"),paid=e("المدفوع"),discount=e("الخصم");for(EditText x:new EditText[]{customer,item,qty,price,paid,discount})content.addView(x);TextView total=t("الإجمالي: 0.00",18);content.addView(total);Button calc=b("حساب الإجمالي");content.addView(calc);calc.setOnClickListener(v->total.setText("الإجمالي: "+fmt(Math.max(0,num(qty)*num(price)-num(discount)))));Button save=b("حفظ وترحيل");content.addView(save);save.setOnClickListener(v->{Cursor c=db.q("SELECT id,qty,cost FROM products WHERE name=?",item.getText().toString().trim());if(!c.moveToFirst()){c.close();toast("الصنف غير موجود");return;}double q=num(qty),pr=num(price),old=c.getDouble(1),cost=c.getDouble(2);if(q<=0){c.close();toast("الكمية غير صحيحة");return;}double next=purchase?old+q:old-q;if(next<0){c.close();toast("الرصيد غير كافٍ");return;}double totalValue=Math.max(0,q*pr-num(discount)),pay=Math.min(Math.max(0,num(paid)),totalValue),remaining=totalValue-pay;long pid=c.getLong(0);c.close();SQLiteDatabase sq=db.getWritableDatabase();sq.beginTransaction();try{ContentValues pv=new ContentValues();pv.put("qty",next);if(purchase)pv.put("cost",pr);sq.update("products",pv,"id=?",new String[]{String.valueOf(pid)});ContentValues tv=new ContentValues();String type=purchase?"PURCHASE":"SALE";tv.put("type",type);tv.put("party",customer.getText().toString().trim());tv.put("total",totalValue);tv.put("paid",pay);tv.put("remaining",remaining);tv.put("created_at",System.currentTimeMillis());long tid=sq.insertOrThrow("transactions",null,tv);ContentValues iv=new ContentValues();iv.put("transaction_id",tid);iv.put("product_id",pid);iv.put("qty",q);iv.put("price",pr);iv.put("cost",cost);iv.put("discount",num(discount));sq.insertOrThrow("invoice_items",null,iv);postJournal(sq,tid,type,totalValue,pay,remaining,q*cost);sq.setTransactionSuccessful();}finally{sq.endTransaction();}toast("تم حفظ الفاتورة وترحيلها محاسبيًا");dashboard();});}

 void party(String table,String title){page(title);EditText n=e("الاسم");content.addView(n);Button add=b("إضافة");content.addView(add);add.setOnClickListener(v->{if(!n.getText().toString().trim().isEmpty())db.exec("INSERT INTO "+table+"(name) VALUES(?)",n.getText().toString());n.setText("");party(table,title);});Cursor c=db.q("SELECT name FROM "+table+" ORDER BY id DESC");while(c.moveToNext())content.addView(t("• "+c.getString(0),16));c.close();}
 void cash(){page("الصندوق والمصروفات");EditText desc=e("البيان"),amt=e("المبلغ");amt.setInputType(2);content.addView(desc);content.addView(amt);Button add=b("تسجيل مصروف");content.addView(add);add.setOnClickListener(v->{double x=num(amt);if(x<=0)return;SQLiteDatabase sq=db.getWritableDatabase();sq.beginTransaction();try{ContentValues tv=new ContentValues();tv.put("type","EXPENSE");tv.put("party",desc.getText().toString());tv.put("total",x);tv.put("paid",x);tv.put("remaining",0);tv.put("created_at",System.currentTimeMillis());long tid=sq.insertOrThrow("transactions",null,tv);postJournal(sq,tid,"EXPENSE",x,x,0,0);sq.setTransactionSuccessful();}finally{sq.endTransaction();}toast("تم تسجيل المصروف وترحيله محاسبيًا");dashboard();});}

 void reports(){page("التقارير والتحليل");Cursor c=db.q("SELECT type,COALESCE(SUM(total),0),COALESCE(SUM(paid),0),COALESCE(SUM(remaining),0) FROM transactions GROUP BY type");while(c.moveToNext())content.addView(t(c.getString(0)+" | الإجمالي "+fmt(c.getDouble(1))+" | المدفوع "+fmt(c.getDouble(2))+" | المتبقي "+fmt(c.getDouble(3)),17));c.close();Cursor p=db.q("SELECT COALESCE(SUM((i.price-i.cost)*i.qty-i.discount),0) FROM invoice_items i JOIN transactions t ON t.id=i.transaction_id WHERE t.type='SALE'");double gp=p.moveToFirst()?p.getDouble(0):0;p.close();Cursor ex=db.q("SELECT COALESCE(SUM(total),0) FROM transactions WHERE type='EXPENSE'");double expense=ex.moveToFirst()?ex.getDouble(0):0;ex.close();content.addView(t("مجمل الربح: "+fmt(gp),20));content.addView(t("صافي الربح التشغيلي: "+fmt(gp-expense),20));Button tb=b("ميزان المراجعة");content.addView(tb);tb.setOnClickListener(v->trialBalance());}

 void backup(){page("النسخ الاحتياطي");Button x=b("تصدير نسخة قاعدة البيانات");content.addView(x);x.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,"SmartCompany-backup.db");startActivityForResult(i,900);});content.addView(t("يمكن حفظ نسخة خارجية الآن. الاستعادة ستضاف بعد اختبار الاستيراد على أجهزة فعلية.",15));}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==900&&result==RESULT_OK&&data!=null){try{InputStream in=new FileInputStream(getDatabasePath("smartcompany2.db"));OutputStream out=getContentResolver().openOutputStream(data.getData());byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.close();toast("تم تصدير النسخة الاحتياطية");}catch(Exception ex){toast("تعذر التصدير");}}}
 void trialBalance(){page("ميزان المراجعة");Cursor c=db.q("SELECT a.code,a.name,COALESCE(SUM(j.debit),0),COALESCE(SUM(j.credit),0) FROM accounts a LEFT JOIN journal_lines j ON j.account_id=a.id GROUP BY a.id ORDER BY a.code");double d=0,cr=0;while(c.moveToNext()){double x=c.getDouble(2),y=c.getDouble(3);d+=x;cr+=y;content.addView(t(c.getString(0)+" — "+c.getString(1)+" | مدين "+fmt(x)+" | دائن "+fmt(y),15));}c.close();content.addView(t("إجمالي المدين: "+fmt(d)+" | الدائن: "+fmt(cr)+" | الفرق: "+fmt(d-cr),18));}
 void postJournal(SQLiteDatabase sq,long tid,String type,double total,double paid,double remaining,double cogs){long cash=accountId(sq,"1010"),recv=accountId(sq,"1100"),inv=accountId(sq,"1200"),sales=accountId(sq,"4000"),payable=accountId(sq,"2100"),expense=accountId(sq,"6000"),cogsAcc=accountId(sq,"5100");long je=sq.insertOrThrow("journal_entries",null,cv("transaction_id",tid,"created_at",System.currentTimeMillis()));if(type.equals("SALE")){line(sq,je,cash,paid,0);line(sq,je,recv,remaining,0);line(sq,je,sales,0,total);line(sq,je,cogsAcc,cogs,0);line(sq,je,inv,0,cogs);}else if(type.equals("PURCHASE")){line(sq,je,inv,total,0);line(sq,je,cash,0,paid);line(sq,je,payable,0,remaining);}else{line(sq,je,expense,total,0);line(sq,je,cash,0,paid);}}
 long accountId(SQLiteDatabase sq,String code){Cursor c=sq.rawQuery("SELECT id FROM accounts WHERE code=?",new String[]{code});long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
 void line(SQLiteDatabase sq,long je,long account,double debit,double credit){ContentValues v=new ContentValues();v.put("journal_entry_id",je);v.put("account_id",account);v.put("debit",debit);v.put("credit",credit);sq.insertOrThrow("journal_lines",null,v);}
 ContentValues cv(Object...a){ContentValues v=new ContentValues();for(int i=0;i<a.length;i+=2){Object val=a[i+1];if(val instanceof Number)v.put(String.valueOf(a[i]),((Number)val).doubleValue());else v.put(String.valueOf(a[i]),String.valueOf(val));}return v;}
 double num(EditText x){try{return Double.parseDouble(x.getText().toString());}catch(Exception z){return 0;}}String fmt(double x){return String.format(Locale.US,"%,.2f",x);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(u)));}catch(Exception z){}}
 public void onBackPressed(){dashboard();}
 static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"smartcompany2.db",null,2);}public void onCreate(SQLiteDatabase d){schema(d);}public void onUpgrade(SQLiteDatabase d,int o,int n){schema(d);}void schema(SQLiteDatabase d){d.execSQL("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,qty REAL NOT NULL DEFAULT 0,sale_price REAL NOT NULL DEFAULT 0,cost REAL NOT NULL DEFAULT 0,reorder REAL NOT NULL DEFAULT 0)");d.execSQL("CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,party TEXT,total REAL NOT NULL,paid REAL NOT NULL DEFAULT 0,remaining REAL NOT NULL DEFAULT 0,created_at INTEGER)");d.execSQL("CREATE TABLE IF NOT EXISTS invoice_items(id INTEGER PRIMARY KEY AUTOINCREMENT,transaction_id INTEGER,product_id INTEGER,qty REAL,price REAL,cost REAL,discount REAL NOT NULL DEFAULT 0)");
 d.execSQL("CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT NOT NULL,type TEXT)");
 d.execSQL("CREATE TABLE IF NOT EXISTS journal_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,transaction_id INTEGER,created_at INTEGER)");
 d.execSQL("CREATE TABLE IF NOT EXISTS journal_lines(id INTEGER PRIMARY KEY AUTOINCREMENT,journal_entry_id INTEGER,account_id INTEGER,debit REAL NOT NULL DEFAULT 0,credit REAL NOT NULL DEFAULT 0)");
 String[][] ac={{"1010","الصندوق","ASSET"},{"1100","العملاء","ASSET"},{"1200","المخزون","ASSET"},{"2100","الموردون","LIABILITY"},{"3000","رأس المال","EQUITY"},{"4000","المبيعات","REVENUE"},{"5100","تكلفة البضاعة المباعة","COST"},{"6000","المصروفات","EXPENSE"}};for(String[] a:ac){ContentValues v=new ContentValues();v.put("code",a[0]);v.put("name",a[1]);v.put("type",a[2]);d.insertWithOnConflict("accounts",null,v,SQLiteDatabase.CONFLICT_IGNORE);}d.execSQL("CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON journal_lines(account_id)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_invoice_items_tx ON invoice_items(transaction_id)");}void exec(String s,Object...a){tx(s,a);}void tx(String s,Object...a){SQLiteDatabase d=getWritableDatabase();SQLiteStatement q=d.compileStatement(s);for(int i=0;i<a.length;i++){Object v=a[i];if(v instanceof Number)q.bindDouble(i+1,((Number)v).doubleValue());else q.bindString(i+1,String.valueOf(v));}q.execute();}Cursor q(String s,String...a){return getReadableDatabase().rawQuery(s,a);}}
}
