package com.mohammedmustafa.smartcompany;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.graphics.Color;import android.print.*;import android.view.*;import android.widget.*;import java.util.*;import java.io.*;

public class MainActivity extends Activity{
 DB db; LinearLayout content; final int green=Color.rgb(11,93,59);
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this); if(!trial()){lock("انتهت التجربة المجانية. الرجاء التواصل مع الدعم.");}else login();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(18,14,18,14);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setPadding(18,8,18,8);return x;}
 void page(String h){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.rgb(248,249,250));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(green);TextView q=t(h,20);q.setTextColor(Color.WHITE);bar.addView(q,new LinearLayout.LayoutParams(0,-2,1));Button home=b("الرئيسية");home.setTextColor(Color.WHITE);home.setOnClickListener(v->dashboard());bar.addView(home);r.addView(bar);ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);s.addView(content);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);}
 boolean trial(){android.content.SharedPreferences p=getSharedPreferences("trial",0);long f=p.getLong("first",0);if(f==0){f=System.currentTimeMillis();p.edit().putLong("first",f).apply();}return System.currentTimeMillis()-f<7L*86400000L;}
 void lock(String msg){page("الاشتراك");content.addView(t(msg,20));Button w=b("التواصل مع الدعم");content.addView(w);w.setOnClickListener(v->open("https://wa.me/249121851285"));content.addView(t("ملاحظة: لا يوجد كود تفعيل ثابت داخل الإصدار 2.0. نظام الترخيص النهائي سيستخدم ترخيصًا موقّعًا من الخادم.",14));}
 void login(){page("شركة محمد مصطفي الذكية");content.addView(t("المحاسبة والمخزون — الإصدار 2.0",24));android.content.SharedPreferences p=getSharedPreferences("security",0);if(!p.contains("pin")){content.addView(t("أنشئ رمز دخول خاصًا بك (4 أرقام على الأقل).",16));EditText x=e("رمز الدخول");x.setInputType(2|0x10);content.addView(x);Button s=b("حفظ الرمز والدخول");content.addView(s);s.setOnClickListener(v->{String z=x.getText().toString();if(z.length()<4){toast("الرمز قصير");return;}p.edit().putString("pin",z).apply();dashboard();});}else{EditText x=e("رمز الدخول");x.setInputType(2|0x10);content.addView(x);Button s=b("دخول");content.addView(s);s.setOnClickListener(v->{if(x.getText().toString().equals(p.getString("pin","")))dashboard();else toast("رمز الدخول غير صحيح");});}}
 void dashboard(){page("لوحة التحكم");content.addView(t("مركز إدارة النشاط",24));content.addView(t(summary(),16));String[] a={"الفواتير والمبيعات","المشتريات","الأصناف والمخزون","العملاء","الموردون","الصندوق والمصروفات","الحسابات البنكية","سجل الشيكات","الموظفون","التقارير والتحليل","النسخ الاحتياطي","الدعم"};for(String n:a){Button x=b(n);content.addView(x);x.setOnClickListener(v->{switch(n){case"الفواتير والمبيعات":invoice(false);break;case"المشتريات":invoice(true);break;case"الأصناف والمخزون":products();break;case"العملاء":party("customers","العملاء");break;case"الموردون":party("suppliers","الموردون");break;case"الصندوق والمصروفات":cash();break;case"الحسابات البنكية":banks();break;case"سجل الشيكات":checks();break;case"الموظفون":party("employees","الموظفون");break;case"التقارير والتحليل":reports();break;case"النسخ الاحتياطي":backup();break;default:open("https://wa.me/249121851285");}});}}
 String summary(){Cursor c=db.q("SELECT COALESCE(SUM(CASE WHEN type='SALE' THEN total ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='PURCHASE' THEN total ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='EXPENSE' THEN total ELSE 0 END),0) FROM transactions");double s=0,p=0,x=0;if(c.moveToFirst()){s=c.getDouble(0);p=c.getDouble(1);x=c.getDouble(2);}c.close();return"المبيعات: "+fmt(s)+" | المشتريات: "+fmt(p)+" | المصروفات: "+fmt(x);}
 void products(){page("الأصناف والمخزون والباركود");EditText n=e("اسم الصنف"),barcode=e("الباركود (امسح بالماسح أو اكتب الرقم)"),q=e("الرصيد الافتتاحي"),p=e("سعر البيع"),c=e("تكلفة الوحدة"),r=e("حد إعادة الطلب");for(EditText x:new EditText[]{n,barcode,q,p,c,r}){x.setInputType(2);if(x==n)x.setInputType(1);content.addView(x);}content.addView(t("يمكن استخدام ماسح USB/Bluetooth الذي يكتب الأرقام كلوحة مفاتيح؛ الكاميرا غير مضافة بعد.",13));Button add=b("إضافة الصنف");content.addView(add);add.setOnClickListener(v->{String name=n.getText().toString().trim(),code=barcode.getText().toString().trim();if(name.isEmpty()){toast("أدخل اسم الصنف");return;}try{db.exec("INSERT INTO products(name,barcode,qty,sale_price,cost,reorder) VALUES(?,?,?,?,?,?)",name,code.isEmpty()?null:code,num(q),num(p),num(c),num(r));toast("تم حفظ الصنف");products();}catch(Exception ex){toast("تعذر الحفظ: تأكد من عدم تكرار الاسم أو الباركود");}});Cursor z=db.q("SELECT name,barcode,qty,sale_price,cost,reorder FROM products ORDER BY id DESC");while(z.moveToNext())content.addView(t(z.getString(0)+" | باركود "+(z.getString(1)==null?"—":z.getString(1))+" | رصيد "+z.getDouble(2)+" | بيع "+fmt(z.getDouble(3))+" | تكلفة "+fmt(z.getDouble(4))+(z.getDouble(2)<=z.getDouble(5)?" | ⚠ إعادة طلب":""),15));z.close();}
 void invoice(boolean purchase){page(purchase?"فاتورة شراء":"فاتورة بيع");EditText customer=e(purchase?"المورد":"العميل"),item=e("اسم الصنف"),qty=e("الكمية"),price=e("السعر"),paid=e("المدفوع"),discount=e("الخصم");for(EditText x:new EditText[]{customer,item,qty,price,paid,discount})content.addView(x);TextView total=t("الإجمالي: 0.00",18);content.addView(total);Button calc=b("حساب الإجمالي");content.addView(calc);calc.setOnClickListener(v->total.setText("الإجمالي: "+fmt(Math.max(0,num(qty)*num(price)-num(discount)))));Button save=b("حفظ وترحيل");content.addView(save);save.setOnClickListener(v->{Cursor c=db.q("SELECT id,qty,cost FROM products WHERE name=? OR barcode=?",item.getText().toString().trim(),item.getText().toString().trim());if(!c.moveToFirst()){c.close();toast("الصنف غير موجود");return;}double q=num(qty),pr=num(price),old=c.getDouble(1),cost=c.getDouble(2);if(q<=0){c.close();toast("الكمية غير صحيحة");return;}double next=purchase?old+q:old-q;if(next<0){c.close();toast("الرصيد غير كافٍ");return;}double totalValue=Math.max(0,q*pr-num(discount)),pay=Math.min(Math.max(0,num(paid)),totalValue),remaining=totalValue-pay;long pid=c.getLong(0);c.close();SQLiteDatabase sq=db.getWritableDatabase();sq.beginTransaction();try{ContentValues pv=new ContentValues();pv.put("qty",next);if(purchase)pv.put("cost",pr);sq.update("products",pv,"id=?",new String[]{String.valueOf(pid)});ContentValues tv=new ContentValues();String type=purchase?"PURCHASE":"SALE";tv.put("type",type);tv.put("party",customer.getText().toString().trim());tv.put("total",totalValue);tv.put("paid",pay);tv.put("remaining",remaining);tv.put("created_at",System.currentTimeMillis());long tid=sq.insertOrThrow("transactions",null,tv);ContentValues iv=new ContentValues();iv.put("transaction_id",tid);iv.put("product_id",pid);iv.put("qty",q);iv.put("price",pr);iv.put("cost",cost);iv.put("discount",num(discount));sq.insertOrThrow("invoice_items",null,iv);postJournal(sq,tid,type,totalValue,pay,remaining,q*cost);sq.setTransactionSuccessful();}finally{sq.endTransaction();}toast("تم حفظ الفاتورة وترحيلها محاسبيًا");dashboard();});}

 void banks(){
  page("الحسابات البنكية");
  content.addView(t("إدارة الحسابات وحركات الإيداع والسحب",16));
  EditText bank=e("اسم البنك"),name=e("اسم الحساب"),opening=e("الرصيد الافتتاحي");
  opening.setInputType(8194);content.addView(bank);content.addView(name);content.addView(opening);
  Button add=b("إضافة حساب بنكي");content.addView(add);
  add.setOnClickListener(v->{if(bank.getText().toString().trim().isEmpty()||name.getText().toString().trim().isEmpty()){toast("أدخل اسم البنك والحساب");return;}try{db.exec("INSERT INTO bank_accounts(bank_name,account_name,opening_balance) VALUES(?,?,?)",bank.getText().toString().trim(),name.getText().toString().trim(),num(opening));toast("تمت إضافة الحساب");banks();}catch(Exception ex){toast("تعذر إضافة الحساب؛ تحقق من البيانات");}});
  content.addView(t("تسجيل حركة بنكية",18));
  EditText account=e("اسم الحساب البنكي كما أُدخل"),amount=e("المبلغ"),note=e("البيان");amount.setInputType(8194);content.addView(account);content.addView(amount);content.addView(note);
  Spinner kind=new Spinner(this);kind.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"إيداع","سحب"}));content.addView(kind);
  Button move=b("حفظ الحركة");content.addView(move);
  move.setOnClickListener(v->{double a=num(amount);if(a<=0){toast("أدخل مبلغًا صحيحًا");return;}Cursor c=db.q("SELECT id FROM bank_accounts WHERE account_name=?",account.getText().toString().trim());if(!c.moveToFirst()){c.close();toast("الحساب البنكي غير موجود");return;}long id=c.getLong(0);c.close();db.exec("INSERT INTO bank_movements(account_id,kind,amount,note,created_at) VALUES(?,?,?,?,?)",id,kind.getSelectedItemPosition()==0?"DEPOSIT":"WITHDRAWAL",a,note.getText().toString().trim(),System.currentTimeMillis());toast("تم تسجيل الحركة");banks();});
  Cursor c=db.q("SELECT b.bank_name,b.account_name,b.opening_balance+COALESCE(SUM(CASE WHEN m.kind='DEPOSIT' THEN m.amount WHEN m.kind='WITHDRAWAL' THEN -m.amount ELSE 0 END),0) FROM bank_accounts b LEFT JOIN bank_movements m ON m.account_id=b.id GROUP BY b.id ORDER BY b.id DESC");
  while(c.moveToNext())content.addView(t(c.getString(0)+" — "+c.getString(1)+" | الرصيد: "+fmt(c.getDouble(2)),15));c.close();
 }
 void checks(){
  page("سجل الشيكات");content.addView(t("سجل الشيكات الواردة والصادرة ومواعيد استحقاقها",16));
  Spinner direction=new Spinner(this);direction.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"شيك وارد","شيك صادر"}));content.addView(direction);
  EditText number=e("رقم الشيك"),bank=e("اسم البنك"),party=e("اسم العميل أو المستفيد"),amount=e("قيمة الشيك"),issue=e("تاريخ الإصدار YYYY-MM-DD"),due=e("تاريخ الاستحقاق YYYY-MM-DD");
  amount.setInputType(8194);for(EditText x:new EditText[]{number,bank,party,amount,issue,due})content.addView(x);
  Spinner status=new Spinner(this);status.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"قيد الانتظار","مستحق","تم التحصيل/الصرف","مرتجع","ملغى"}));content.addView(status);
  Button save=b("حفظ الشيك");content.addView(save);
  save.setOnClickListener(v->{if(number.getText().toString().trim().isEmpty()||num(amount)<=0||due.getText().toString().trim().isEmpty()){toast("رقم الشيك والقيمة وتاريخ الاستحقاق مطلوبة");return;}String[] states={"PENDING","DUE","CLEARED","RETURNED","CANCELLED"};try{db.exec("INSERT INTO checks(direction,check_no,bank_name,party,amount,issue_date,due_date,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)",direction.getSelectedItemPosition()==0?"INCOMING":"OUTGOING",number.getText().toString().trim(),bank.getText().toString().trim(),party.getText().toString().trim(),num(amount),issue.getText().toString().trim(),due.getText().toString().trim(),states[status.getSelectedItemPosition()],System.currentTimeMillis());toast("تم حفظ الشيك");checks();}catch(Exception ex){toast("تعذر حفظ الشيك؛ ربما رقم الشيك مسجل مسبقًا");}});
  content.addView(t("تحديث حالة شيك محفوظ",17));EditText updateNo=e("رقم الشيك المراد تحديثه");content.addView(updateNo);Spinner updateStatus=new Spinner(this);updateStatus.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"قيد الانتظار","مستحق","تم التحصيل/الصرف","مرتجع","ملغى"}));content.addView(updateStatus);Button update=b("تحديث حالة الشيك");content.addView(update);update.setOnClickListener(v->{String[] states={"PENDING","DUE","CLEARED","RETURNED","CANCELLED"};db.exec("UPDATE checks SET status=? WHERE check_no=?",states[updateStatus.getSelectedItemPosition()],updateNo.getText().toString().trim());toast("تم تحديث الحالة إن كان رقم الشيك موجودًا");checks();});
  Cursor c=db.q("SELECT direction,check_no,bank_name,party,amount,due_date,status FROM checks ORDER BY due_date ASC,id DESC");
  while(c.moveToNext()){String d=c.getString(0).equals("INCOMING")?"وارد":"صادر";String st=c.getString(6);String label=st.equals("PENDING")?"قيد الانتظار":st.equals("DUE")?"مستحق":st.equals("CLEARED")?"تم التحصيل/الصرف":st.equals("RETURNED")?"مرتجع":"ملغى";content.addView(t(d+" | شيك "+c.getString(1)+" | "+c.getString(2)+" | "+c.getString(3)+" | "+fmt(c.getDouble(4))+" | الاستحقاق "+c.getString(5)+" | "+label,14));}c.close();
 }
 void party(String table,String title){page(title);EditText n=e("الاسم");content.addView(n);Button add=b("إضافة");content.addView(add);add.setOnClickListener(v->{if(!n.getText().toString().trim().isEmpty())db.exec("INSERT INTO "+table+"(name) VALUES(?)",n.getText().toString());n.setText("");party(table,title);});Cursor c=db.q("SELECT name FROM "+table+" ORDER BY id DESC");while(c.moveToNext())content.addView(t("• "+c.getString(0),16));c.close();}
 void cash(){page("الصندوق والمصروفات");EditText desc=e("البيان"),amt=e("المبلغ");amt.setInputType(2);content.addView(desc);content.addView(amt);Button add=b("تسجيل مصروف");content.addView(add);add.setOnClickListener(v->{double x=num(amt);if(x<=0)return;SQLiteDatabase sq=db.getWritableDatabase();sq.beginTransaction();try{ContentValues tv=new ContentValues();tv.put("type","EXPENSE");tv.put("party",desc.getText().toString());tv.put("total",x);tv.put("paid",x);tv.put("remaining",0);tv.put("created_at",System.currentTimeMillis());long tid=sq.insertOrThrow("transactions",null,tv);postJournal(sq,tid,"EXPENSE",x,x,0,0);sq.setTransactionSuccessful();}finally{sq.endTransaction();}toast("تم تسجيل المصروف وترحيله محاسبيًا");dashboard();});}

 void reports(){page("التقارير والتحليل");Cursor c=db.q("SELECT type,COALESCE(SUM(total),0),COALESCE(SUM(paid),0),COALESCE(SUM(remaining),0) FROM transactions GROUP BY type");while(c.moveToNext())content.addView(t(c.getString(0)+" | الإجمالي "+fmt(c.getDouble(1))+" | المدفوع "+fmt(c.getDouble(2))+" | المتبقي "+fmt(c.getDouble(3)),17));c.close();Cursor p=db.q("SELECT COALESCE(SUM((i.price-i.cost)*i.qty-i.discount),0) FROM invoice_items i JOIN transactions t ON t.id=i.transaction_id WHERE t.type='SALE'");double gp=p.moveToFirst()?p.getDouble(0):0;p.close();Cursor ex=db.q("SELECT COALESCE(SUM(total),0) FROM transactions WHERE type='EXPENSE'");double expense=ex.moveToFirst()?ex.getDouble(0):0;ex.close();content.addView(t("مجمل الربح: "+fmt(gp),20));content.addView(t("صافي الربح التشغيلي: "+fmt(gp-expense),20));Button tb=b("ميزان المراجعة");content.addView(tb);tb.setOnClickListener(v->trialBalance());}

 void backup(){page("النسخ الاحتياطي");Button x=b("تصدير نسخة قاعدة البيانات");content.addView(x);x.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,"SmartCompany-backup.db");startActivityForResult(i,900);});content.addView(t("يمكن حفظ نسخة خارجية الآن. الاستعادة ستضاف بعد اختبار الاستيراد على أجهزة فعلية.",15));}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==900&&result==RESULT_OK&&data!=null){try{InputStream in=new FileInputStream(getDatabasePath("smartcompany2.db"));OutputStream out=getContentResolver().openOutputStream(data.getData());byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.close();toast("تم تصدير النسخة الاحتياطية");}catch(Exception ex){toast("تعذر التصدير");}}}
 void trialBalance(){page("ميزان المراجعة");Cursor c=db.q("SELECT a.code,a.name,COALESCE(SUM(j.debit),0),COALESCE(SUM(j.credit),0) FROM accounts a LEFT JOIN journal_lines j ON j.account_id=a.id GROUP BY a.id ORDER BY a.code");double d=0,cr=0;while(c.moveToNext()){double x=c.getDouble(2),y=c.getDouble(3);d+=x;cr+=y;content.addView(t(c.getString(0)+" — "+c.getString(1)+" | مدين "+fmt(x)+" | دائن "+fmt(y),15));}c.close();content.addView(t("إجمالي المدين: "+fmt(d)+" | الدائن: "+fmt(cr)+" | الفرق: "+fmt(d-cr),18));}
 void postJournal(SQLiteDatabase sq,long tid,String type,double total,double paid,double remaining,double cogs){long cash=accountId(sq,"1010"),recv=accountId(sq,"1100"),inv=accountId(sq,"1200"),sales=accountId(sq,"4000"),payable=accountId(sq,"2100"),expense=accountId(sq,"6000"),cogsAcc=accountId(sq,"5100");long je=sq.insertOrThrow("journal_entries",null,cv("transaction_id",tid,"created_at",System.currentTimeMillis()));if(type.equals("SALE")){line(sq,je,cash,paid,0);line(sq,je,recv,remaining,0);line(sq,je,sales,0,total);line(sq,je,cogsAcc,cogs,0);line(sq,je,inv,0,cogs);}else if(type.equals("PURCHASE")){line(sq,je,inv,total,0);line(sq,je,cash,0,paid);line(sq,je,payable,0,remaining);}else{line(sq,je,expense,total,0);line(sq,je,cash,0,paid);}}
 long accountId(SQLiteDatabase sq,String code){Cursor c=sq.rawQuery("SELECT id FROM accounts WHERE code=?",new String[]{code});long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
 void line(SQLiteDatabase sq,long je,long account,double debit,double credit){ContentValues v=new ContentValues();v.put("journal_entry_id",je);v.put("account_id",account);v.put("debit",debit);v.put("credit",credit);sq.insertOrThrow("journal_lines",null,v);}
 ContentValues cv(Object...a){ContentValues v=new ContentValues();for(int i=0;i<a.length;i+=2){Object val=a[i+1];if(val instanceof Number)v.put(String.valueOf(a[i]),((Number)val).doubleValue());else v.put(String.valueOf(a[i]),String.valueOf(val));}return v;}
 double num(EditText x){try{return Double.parseDouble(x.getText().toString());}catch(Exception z){return 0;}}String fmt(double x){return String.format(Locale.US,"%,.2f",x);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(u)));}catch(Exception z){}}
 public void onBackPressed(){dashboard();}
 static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"smartcompany2.db",null,3);}public void onCreate(SQLiteDatabase d){schema(d);}public void onUpgrade(SQLiteDatabase d,int o,int n){schema(d);}void schema(SQLiteDatabase d){d.execSQL("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,qty REAL NOT NULL DEFAULT 0,sale_price REAL NOT NULL DEFAULT 0,cost REAL NOT NULL DEFAULT 0,reorder REAL NOT NULL DEFAULT 0)");try{d.execSQL("ALTER TABLE products ADD COLUMN barcode TEXT");}catch(Exception ignored){}d.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode) WHERE barcode IS NOT NULL AND barcode != ''");d.execSQL("CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,party TEXT,total REAL NOT NULL,paid REAL NOT NULL DEFAULT 0,remaining REAL NOT NULL DEFAULT 0,created_at INTEGER)");d.execSQL("CREATE TABLE IF NOT EXISTS invoice_items(id INTEGER PRIMARY KEY AUTOINCREMENT,transaction_id INTEGER,product_id INTEGER,qty REAL,price REAL,cost REAL,discount REAL NOT NULL DEFAULT 0)");
 d.execSQL("CREATE TABLE IF NOT EXISTS bank_accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,bank_name TEXT NOT NULL,account_name TEXT NOT NULL UNIQUE,opening_balance REAL NOT NULL DEFAULT 0)");
 d.execSQL("CREATE TABLE IF NOT EXISTS bank_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,account_id INTEGER NOT NULL,kind TEXT NOT NULL,amount REAL NOT NULL,note TEXT,created_at INTEGER)");
 d.execSQL("CREATE TABLE IF NOT EXISTS checks(id INTEGER PRIMARY KEY AUTOINCREMENT,direction TEXT NOT NULL,check_no TEXT NOT NULL,bank_name TEXT,party TEXT,amount REAL NOT NULL,issue_date TEXT,due_date TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER,UNIQUE(direction,check_no))");
 d.execSQL("CREATE INDEX IF NOT EXISTS idx_checks_due_status ON checks(due_date,status)");
 d.execSQL("CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT NOT NULL,type TEXT)");
 d.execSQL("CREATE TABLE IF NOT EXISTS journal_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,transaction_id INTEGER,created_at INTEGER)");
 d.execSQL("CREATE TABLE IF NOT EXISTS journal_lines(id INTEGER PRIMARY KEY AUTOINCREMENT,journal_entry_id INTEGER,account_id INTEGER,debit REAL NOT NULL DEFAULT 0,credit REAL NOT NULL DEFAULT 0)");
 String[][] ac={{"1010","الصندوق","ASSET"},{"1100","العملاء","ASSET"},{"1200","المخزون","ASSET"},{"2100","الموردون","LIABILITY"},{"3000","رأس المال","EQUITY"},{"4000","المبيعات","REVENUE"},{"5100","تكلفة البضاعة المباعة","COST"},{"6000","المصروفات","EXPENSE"}};for(String[] a:ac){ContentValues v=new ContentValues();v.put("code",a[0]);v.put("name",a[1]);v.put("type",a[2]);d.insertWithOnConflict("accounts",null,v,SQLiteDatabase.CONFLICT_IGNORE);}d.execSQL("CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON journal_lines(account_id)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_invoice_items_tx ON invoice_items(transaction_id)");}void exec(String s,Object...a){tx(s,a);}void tx(String s,Object...a){SQLiteDatabase d=getWritableDatabase();SQLiteStatement q=d.compileStatement(s);for(int i=0;i<a.length;i++){Object v=a[i];if(v instanceof Number)q.bindDouble(i+1,((Number)v).doubleValue());else q.bindString(i+1,String.valueOf(v));}q.execute();}Cursor q(String s,String...a){return getReadableDatabase().rawQuery(s,a);}}
}
