const SYSTEM_PROMPT = `أنت الوكيل الذكي ومسؤول المبيعات الودود لمنصة الموسوعات الذكية.
هدفك ليس مجرد الإجابة، بل تحويل الزائر المتردد إلى مشتري مقتنع من خلال حوار إنساني ودود ومهني: افهم حاجته أولاً، أبرز القيمة المناسبة له، أجب بدقة، ثم اقترح خطوة شراء واضحة. كن واثقاً وباسلاً في البيع دون ضغط مزعج أو كذب أو وعود غير موجودة. لا تختلق شهادات أو تقييمات أو أعداد مبيعات أو ضمانات أو مزايا غير معلنة.

أسلوب الحوار:
- خاطب الزائر بالعربية الواضحة الدافئة، وبأسلوب مستشار مبيعات حقيقي يفهم المنتج.
- لا تكرر قائمة مواصفات جافة. اربط الميزة بفائدة للزائر.
- إذا سأل عن السعر، أجب بالسعر المطلوب والكمية والإجمالي والتوفير إن كانت الكمية معروفة، ولا تكتفِ بسعر النسخة الواحدة.
- إذا ذكر عدداً من النسخ، احسب الإجمالي مباشرة. العرض الحالي لأول 200 نسخة: 120,000 جنيه للنسخة بدلاً من 150,000، أو 16 دولاراً للنسخة بدلاً من 19 دولاراً.
- إذا كانت الكمية أكبر من 200، احسب أول 200 بسعر العرض والباقي بالسعر الأساسي، ووضح ذلك.
- إذا لم يذكر العملة، أعطه الجنيه السوداني أولاً ثم الدولار.
- عند وجود نية شراء واضحة، لا تكتفِ بعبارة عامة مثل "يمكنك الشراء"؛ وجّه الزائر إلى صفحة الدفع أو واتساب.
- استخدم المعاينة كوسيلة لبناء الثقة: 20 صفحة حقيقية متاحة للمعاينة قبل الشراء.
- أبرز القيمة: موسوعة كاملة من 250 صفحة + وكيل ذكي مع النسخة الكاملة، مع مسار تعليمي من الأساسيات إلى التطبيقات والمشاريع.
- إذا كان السؤال عن الطلاب أو مؤسسة أو عدة نسخ، اقترح شراء النسخ المطلوبة واذكر إجمالي الكمية.
- لا تضغط على الزائر ولا تدّعي أن العرض سينتهي اليوم. العرض المعلن فقط هو لأول 200 نسخة.

بيانات المنتج المعتمدة:
السعر الأساسي 150000 جنيه سوداني للنسخة.
العرض لأول 200 نسخة: خصم 20%، والسعر 120000 جنيه سوداني للنسخة.
السعر بالدولار 19، وسعر العرض لأول 200 نسخة 16 دولاراً.
الموسوعة الكاملة 250 صفحة، والمعاينة 20 صفحة.
النسخة الكاملة تشمل وكيلاً ذكياً للمشتري يساعد في شرح المفاهيم وتبسيط المصطلحات والإجابة عن الأسئلة.
الدفع المحلي عبر بنك الخرطوم/بنكك للحساب 1882224.
الدفع بالدولار عبر IBAN: SD8504018822240001.
واتساب: +249121851285.

المزايا التعليمية تشمل المفاهيم الأساسية، تعلم الآلة، التعلم العميق، NLP، النماذج اللغوية الكبيرة، الذكاء التوليدي، هندسة الأوامر، RAG، الوكلاء، الرؤية الحاسوبية، الذكاء متعدد الوسائط، الحوكمة، التطبيقات والمشاريع.
التحديثات المستقبلية المعلنة تُقدم للمستخدم كتحديثات قادمة فقط، وليست ميزات متاحة الآن.
لا تدّعِ أن الوكيل يقرأ كامل النسخة المدفوعة أو ينفذ عمليات خارج الموقع ما لم يظهر ذلك في البيانات المتاحة.
لا تطلب رقم بطاقة أو كلمة مرور أو مفتاح API.
إذا طلب المستخدم تنفيذ مهمة داخل الموقع، أعد إجراءاً من القائمة المسموحة فقط.
الإجراءات المسموحة: open_preview, open_preview_page, open_whatsapp, focus_offer, open_checkout.
أعد JSON فقط بالشكل: {"reply":"...","actions":[{"type":"...","page":1}]}`;

const ALLOWED_ACTIONS = new Set(["open_preview", "open_preview_page", "open_whatsapp", "focus_offer", "open_checkout"]);
function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "content-type, authorization" } }); }
function corsPreflight() { return new Response(null, { status: 204, headers: { "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "content-type, authorization" } }); }
function sanitizeActions(actions) { if (!Array.isArray(actions)) return []; return actions.filter((a) => a && ALLOWED_ACTIONS.has(a.type)).slice(0, 3).map((a) => { const out = { type: a.type }; if (a.type === "open_preview_page") { const page = Number(a.page); if (Number.isInteger(page) && page >= 1 && page <= 20) out.page = page; else return null; } return out; }).filter(Boolean); }
async function callGemini(message, env) { if (!env.GEMINI_API_KEY) throw new Error("GEMINI_API_KEY is not configured"); const model = env.GEMINI_MODEL || "gemini-2.5-flash"; const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`; const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] }, contents: [{ role: "user", parts: [{ text: message }] }], generationConfig: { temperature: 0.35, responseMimeType: "application/json" } }) }); if (!response.ok) throw new Error(`Gemini request failed: ${response.status}`); const data = await response.json(); const text = data?.candidates?.[0]?.content?.parts?.map((p) => p.text || "").join("") || ""; if (!text) throw new Error("Empty model response"); return JSON.parse(text); }
function normalizeDigits(s) { return String(s || "").replace(/[٠-٩]/g, (d) => String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/٫/g, "."); }
function quantityFromMessage(message) { const q = normalizeDigits(message).toLowerCase(); const m = q.match(/(?:^|\s)(\d{1,5})\s*(?:نسخ(?:ة)?|copy|copies|طبعة|كتاب)/i) || q.match(/(?:كم|عدد)\s*(?:من\s*)?(\d{1,5})/i); return m ? Math.max(1, Math.min(10000, Number(m[1]))) : null; }
function salesQuantityReply(message) { const q = quantityFromMessage(message); const text = String(message || "").toLowerCase(); if (!q) return null; const usd = text.includes("دولار") || text.includes("usd") || text.includes("$" ) || text.includes("دولاري"); const offer = Math.min(q, 200); const regular = Math.max(0, q - 200); if (usd) { const total = offer * 16 + regular * 19; const normal = q * 19; const saving = normal - total; return { reply: `أكيد. لعدد ${q} نسخة: ${offer} نسخة ضمن عرض أول 200 نسخة بسعر 16 دولاراً للنسخة${regular ? `، و${regular} نسخة بالسعر الأساسي 19 دولاراً` : ""}. الإجمالي ${total} دولار، والتوفير ${saving} دولار مقارنة بالسعر الأساسي. إذا كنت جاهزاً، أفتح لك صفحة الشراء الآن.`, actions: [{ type: "open_checkout" }] }; } const total = offer * 120000 + regular * 150000; const normal = q * 150000; const saving = normal - total; return { reply: `أكيد 👍 لعدد ${q} نسخة: ${offer} نسخة ضمن عرض أول 200 نسخة بسعر 120,000 ج.س للنسخة${regular ? `، و${regular} نسخة بالسعر الأساسي 150,000 ج.س` : ""}. الإجمالي ${total.toLocaleString("en-US")} جنيه سوداني، والتوفير ${saving.toLocaleString("en-US")} جنيه مقارنة بالسعر الأساسي. إذا كان العدد لمؤسسة أو مجموعة طلابية، فهذا يوفر مبلغاً جيداً، ويمكنني توجيهك مباشرة لإتمام الطلب.`, actions: [{ type: "open_checkout" }] }; }
function fallbackAgent(message) { const q = String(message || "").trim().toLowerCase(); const bulk = salesQuantityReply(message); if (bulk) return bulk; if (q.includes("سعر") || q.includes("كم") || q.includes("دولار") || q.includes("جنيه") || q.includes("دفع")) return { reply: "أهلاً بك 🌟 السعر الأساسي 150,000 جنيه سوداني، لكن العرض الحالي لأول 200 نسخة يخفضه إلى 120,000 جنيه للنسخة. وبالدولار 19 دولاراً، أو 16 دولاراً ضمن العرض. النسخة الكاملة 250 صفحة وتشمل الوكيل الذكي، ويمكنك معاينة 20 صفحة حقيقية قبل الشراء. إذا أخبرتني بعدد النسخ أحسب لك الإجمالي والتوفير فوراً.", actions: [{ type: "focus_offer" }] }; if (q.includes("وكيل") || q.includes("مساعد")) return { reply: "بكل سرور 🤝 الوكيل الذكي جزء من النسخة الكاملة، ومهمته أن يكون معك كمساعد تعليمي: يشرح المفاهيم، يبسط المصطلحات، ويجيب عن أسئلتك ويساعدك على الوصول إلى نقطة البداية المناسبة. وإذا كانت لديك حاجة محددة، أخبرني بها وسأوضح لك كيف تخدمك الموسوعة.", actions: [] }; if (q.includes("معاينة") || q.includes("20") || q.includes("صفحة")) { const match = q.match(/(?:صفحة|page)\s*(\d{1,2})/); if (match) return { reply: `ممتاز. سأفتح لك صفحة ${match[1]} من المعاينة المتاحة. يمكنك الاطلاع بنفسك على جودة المحتوى قبل اتخاذ قرار الشراء.`, actions: [{ type: "open_preview_page", page: Number(match[1]) }] }; return { reply: "أنصحك بالبدء بالمعاينة المجانية: 20 صفحة حقيقية من الموسوعة. شاهد المحتوى بنفسك، وإذا وجدت أنها مناسبة لهدفك أساعدك في إكمال الشراء.", actions: [{ type: "open_preview" }] }; } if (q.includes("شراء") || q.includes("أريد") || q.includes("اريد")) return { reply: "رائع 🌟 إذا كنت مستعداً، فالنسخة الكاملة تمنحك 250 صفحة + الوكيل الذكي، والعرض الحالي لأول 200 نسخة بسعر 120,000 ج.س أو 16 دولاراً. أفتح لك صفحة الشراء لتكمل الطلب بسهولة.", actions: [{ type: "open_checkout" }] }; if (q.includes("واتساب") || q.includes("whatsapp")) return { reply: "بكل سرور. يمكنك التواصل مباشرة عبر واتساب لإتمام الشراء أو الاستفسار عن الطلب، وسأترك لك الطريق المباشر للتواصل.", actions: [{ type: "open_whatsapp" }] }; if (q.includes("محتوى") || q.includes("ماذا") || q.includes("تعلم")) return { reply: "إذا كان هدفك تعلم الذكاء الاصطناعي بصورة متدرجة، فالموسوعة تجمع 250 صفحة من الأساسيات إلى التطبيقات والمشاريع، وتشمل تعلم الآلة والتعلم العميق وNLP وLLMs وهندسة الأوامر وRAG والوكلاء والرؤية الحاسوبية والذكاء متعدد الوسائط والحوكمة. ويمكنك اختبار الجودة بنفسك من خلال المعاينة المجانية قبل الشراء.", actions: [{ type: "open_preview" }] }; return { reply: "مرحباً بك 🌟 أنا هنا لأساعدك لاختيار ما يناسبك، وليس فقط لإعطائك معلومات جافة. أخبرني: هل تريد معرفة السعر، محتوى الموسوعة، قيمة الوكيل الذكي، المعاينة، أم تريد البدء بالشراء؟", actions: [] }; }
async function ensureOrdersTable(env) { if (!env.DB) throw new Error("D1 binding DB is not configured"); await env.DB.prepare(`CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, customer_name TEXT NOT NULL, customer_email TEXT NOT NULL, customer_phone TEXT, product TEXT NOT NULL, currency TEXT NOT NULL, amount INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run(); await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at)`).run(); }
function validEmail(value) { return typeof value === "string" && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) && value.length <= 254; }
async function createOrder(request, env) { await ensureOrdersTable(env); const body = await request.json(); const name = typeof body?.customerName === "string" ? body.customerName.trim() : ""; const email = typeof body?.customerEmail === "string" ? body.customerEmail.trim() : ""; const phone = typeof body?.customerPhone === "string" ? body.customerPhone.trim().slice(0, 40) : ""; const currency = body?.currency === "USD" ? "USD" : "SDG"; const amount = currency === "USD" ? (Number(body?.amount) === 16 ? 16 : 19) : (Number(body?.amount) === 120000 ? 120000 : 150000); if (name.length < 2 || name.length > 120 || !validEmail(email)) return json({ error: "invalid_customer_data" }, 400); const id = crypto.randomUUID(); await env.DB.prepare(`INSERT INTO orders (id, customer_name, customer_email, customer_phone, product, currency, amount) VALUES (?, ?, ?, ?, ?, ?, ?)`).bind(id, name, email, phone, "الموسوعة الشاملة في الذكاء الاصطناعي + الوكيل الذكي", currency, amount).run(); return json({ ok: true, orderId: id, status: "pending" }); }
async function listOrders(request, env) { const expected = env.ADMIN_API_TOKEN; const provided = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") || ""; if (!expected || provided !== expected) return json({ error: "unauthorized" }, 401); await ensureOrdersTable(env); const result = await env.DB.prepare(`SELECT id, customer_name, customer_email, customer_phone, product, currency, amount, status, created_at FROM orders ORDER BY created_at DESC LIMIT 100`).all(); return json({ ok: true, orders: result.results || [] }); }
export default { async fetch(request, env) { if (request.method === "OPTIONS") return corsPreflight(); const url = new URL(request.url); if (url.pathname === "/health") return json({ ok: true, service: "smart-encyclopedias-agent", d1: Boolean(env.DB), gemini: Boolean(env.GEMINI_API_KEY), time: new Date().toISOString() }); if (url.pathname === "/api/order" && request.method === "POST") { try { return await createOrder(request, env); } catch (error) { return json({ error: "order_unavailable", message: "تعذر تسجيل الطلب الآن." }, 503); } } if (url.pathname === "/api/orders" && request.method === "GET") { try { return await listOrders(request, env); } catch (error) { return json({ error: "orders_unavailable" }, 503); } } if (url.pathname !== "/api/agent") return json({ error: "Not found" }, 404); if (request.method !== "POST") return json({ error: "Method not allowed" }, 405); try { const body = await request.json(); const message = typeof body?.message === "string" ? body.message.trim() : ""; if (!message || message.length > 2000) return json({ error: "Invalid message" }, 400); let result; try { result = await callGemini(message, env); } catch (_) { result = fallbackAgent(message); } const reply = typeof result?.reply === "string" ? result.reply.slice(0, 5000) : "لم أتمكن من إعداد إجابة الآن."; return json({ reply, actions: sanitizeActions(result?.actions) }); } catch (error) { return json({ error: "agent_unavailable", message: "تعذر معالجة الطلب الآن." }, 503); } } };